/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DispositivoRedeController;
import java.security.NoSuchAlgorithmException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import model.Cliente;
import model.DispositivoDeRede;
import model.exceptions.DispositivoRedeException;

/**
 *
 * @author diego
 */
public class dlgCadastrarDispositivoRede extends javax.swing.JFrame {
    DispositivoRedeController dispositivoRedeController;
    Long idDispositivoEditando;
    

    /**
     * Creates new form dlgCadastroServico
     */
    public dlgCadastrarDispositivoRede() {
        dispositivoRedeController = new DispositivoRedeController();
        initComponents();
        this.criarMascaraCampos();
        idDispositivoEditando = -1L;
        this.habilitarCampos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        lblTitulo5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdDispositivosRede = new javax.swing.JTable();
        panBotoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        panCampos1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        edtPreco = new javax.swing.JTextField();
        lblIP = new javax.swing.JLabel();
        fEdtIP = new javax.swing.JFormattedTextField();
        lblTipo = new javax.swing.JLabel();
        edtTipo = new javax.swing.JTextField();
        panCampos2 = new javax.swing.JPanel();
        lblFabricante = new javax.swing.JLabel();
        edtFabricante = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        edtModelo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitulo5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTitulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo5.setText("Cadastrar dispositivo de Rede");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo5, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        grdDispositivosRede.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        grdDispositivosRede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdDispositivosRedeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grdDispositivosRede);

        panBotoes.setLayout(new javax.swing.BoxLayout(panBotoes, javax.swing.BoxLayout.LINE_AXIS));

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        panBotoes.add(btnNovo);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panBotoes.add(btnEditar);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        panBotoes.add(btnExcluir);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panBotoes.add(btnCancelar);

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        panBotoes.add(btnConfirmar);

        panCampos1.setLayout(new javax.swing.BoxLayout(panCampos1, javax.swing.BoxLayout.LINE_AXIS));

        lblNome.setText("Nome:");
        panCampos1.add(lblNome);
        panCampos1.add(edtNome);

        lblPreco.setText("Preço:");
        panCampos1.add(lblPreco);
        panCampos1.add(edtPreco);

        lblIP.setText("IP:");
        panCampos1.add(lblIP);
        panCampos1.add(fEdtIP);

        lblTipo.setText("Tipo:");
        panCampos1.add(lblTipo);
        panCampos1.add(edtTipo);

        panCampos2.setLayout(new javax.swing.BoxLayout(panCampos2, javax.swing.BoxLayout.LINE_AXIS));

        lblFabricante.setText("Fabricante:");
        panCampos2.add(lblFabricante);
        panCampos2.add(edtFabricante);

        lblModelo.setText("Modelo:");
        panCampos2.add(lblModelo);
        panCampos2.add(edtModelo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panCampos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panCampos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panCampos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panCampos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void grdDispositivosRedeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdDispositivosRedeMouseClicked

    }//GEN-LAST:event_grdDispositivosRedeMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.limparCampos();
        this.habilitarCampos(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        DispositivoDeRede dispositivoRedeEditando = (DispositivoDeRede) this.getObjetoSelecionadoNaGrid();

        if (dispositivoRedeEditando == null)
            JOptionPane.showMessageDialog(this, "Primeiro selecione um registro na tabela.");
        else {
            this.limparCampos();
            this.habilitarCampos(true);
            this.preencherFormulario(dispositivoRedeEditando);
            this.idDispositivoEditando = dispositivoRedeEditando.getId();
        }  
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        idDispositivoEditando = -1L;
        this.limparCampos();
        this.habilitarCampos(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
            if (idDispositivoEditando > 0) {
                dispositivoRedeController.atualizarDispositivoRede();
            } else {
                dispositivoRedeController.cadastrarDispositivoRede();            
            }
            
            //Comando bastante importante
            this.idDispositivoEditando = -1L;

            //idDispositivoEditando.atualizarTabela(grdDispositivosRede);

            this.habilitarCampos(false);
            this.limparCampos();
        } catch (DispositivoRedeException e) {
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(dlgCadastrarTecnico.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        DispositivoDeRede dispositivoRedeExcluido = (DispositivoDeRede) this.getObjetoSelecionadoNaGrid();

        if (dispositivoRedeExcluido == null)
            JOptionPane.showMessageDialog(this, "Primeiro selecione um registro na tabela.");
        else {
            int response = JOptionPane.showConfirmDialog(null,
                    "Deseja exlcuir o Dispositivo mesmo?  \n("
                    + dispositivoRedeExcluido.getNome() + ", "
                    + dispositivoRedeExcluido.getEnderecoIP()+ ") ?",
                    "Confirmar exclusão",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.OK_OPTION) {
                try {
                    dispositivoRedeController.excluirDispositivoRede();

                    dispositivoRedeController.atualizarTabela(grdDispositivosRede);
                    JOptionPane.showMessageDialog(this, "Exclusão feita com sucesso!");
                } catch (DispositivoRedeException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    public void habilitarCampos(boolean flag) {
        for (int i = 0; i < panCampos1.getComponents().length; i++) {
            panCampos1.getComponent(i).setEnabled(flag);
        }
        for (int i = 0; i < panCampos2.getComponents().length; i++) {
            panCampos2.getComponent(i).setEnabled(flag);
        }
    }
    
    public void limparCampos() {
        edtNome.setText("");
        edtFabricante.setText("");
        edtModelo.setText("");
        edtPreco.setText("");
        edtTipo.setText("");
        fEdtIP.setText("");
    }
    
    public void preencherFormulario(DispositivoDeRede dr) {
        edtNome.setText(dr.getNome());
        edtFabricante.setText(dr.getFabricante());
        edtModelo.setText(dr.getModelo());
        edtPreco.setText(String.valueOf(dr.getPreco()));
        edtTipo.setText(dr.getTipo());
        fEdtIP.setText(dr.getEnderecoIP());
    }
    
    private void criarMascaraCampos(){
        try {
            MaskFormatter ipMask = new MaskFormatter("###.###.#.###");
            ipMask.install(fEdtIP);
        } catch (ParseException ex) {
            Logger.getLogger(dlgCadastrarDispositivoRede.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private Object getObjetoSelecionadoNaGrid() {
        int rowCliked = grdDispositivosRede.getSelectedRow();
        Object obj = null;
        if (rowCliked >= 0) {
            obj = grdDispositivosRede.getModel().getValueAt(rowCliked, -1);
        }
        return obj;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgCadastrarDispositivoRede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgCadastrarDispositivoRede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgCadastrarDispositivoRede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgCadastrarDispositivoRede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dlgCadastrarDispositivoRede().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JTextField edtFabricante;
    private javax.swing.JTextField edtModelo;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtPreco;
    private javax.swing.JTextField edtTipo;
    private javax.swing.JFormattedTextField fEdtIP;
    private javax.swing.JTable grdDispositivosRede;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFabricante;
    private javax.swing.JLabel lblIP;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo5;
    private javax.swing.JPanel panBotoes;
    private javax.swing.JPanel panCampos1;
    private javax.swing.JPanel panCampos2;
    // End of variables declaration//GEN-END:variables
}
