/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ConsertoComputadorController;
import controller.ServicoController;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class dlgCadastrarConcertoComputador extends javax.swing.JDialog {
    ServicoController servicoController;
    ConsertoComputadorController consertoController;
    
    /**
     * Creates new form dlgCadastrarConcertoComputador
     */
    public dlgCadastrarConcertoComputador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        servicoController = new ServicoController();
        servicoController.atualizarTabelaCliente(grdClientes);
        servicoController.atualizarTabelaTecnico(grdTecnicos);
        this.habilitarCampos(false);
        
        // Instanciando
        consertoController = new ConsertoComputadorController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSelecaoCliente = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        grdClientes = new javax.swing.JTable();
        lblSelecaoTecnico = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdComputadores = new javax.swing.JTable();
        panProblema = new javax.swing.JPanel();
        lblDescreverProblema = new javax.swing.JLabel();
        edtDescricaoProblema = new javax.swing.JTextField();
        panPecasSubstituidas = new javax.swing.JPanel();
        lblSelecaoPeca = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstPecasSubstituidas = new javax.swing.JList<>();
        panBotoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        grdTecnicos = new javax.swing.JTable();
        lblComputadores = new javax.swing.JLabel();
        panValor = new javax.swing.JPanel();
        lblValor = new javax.swing.JLabel();
        edtValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastrar Conserto Computador");

        javax.swing.GroupLayout panTituloLayout = new javax.swing.GroupLayout(panTitulo);
        panTitulo.setLayout(panTituloLayout);
        panTituloLayout.setHorizontalGroup(
            panTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panTituloLayout.setVerticalGroup(
            panTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblSelecaoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelecaoCliente.setText("Selecione o Cliente");

        grdClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        grdClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(grdClientes);

        lblSelecaoTecnico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelecaoTecnico.setText("Selecione o Técnico");

        grdComputadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        grdComputadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdComputadoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grdComputadores);

        lblDescreverProblema.setText("Descreva o problema:");

        edtDescricaoProblema.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panProblemaLayout = new javax.swing.GroupLayout(panProblema);
        panProblema.setLayout(panProblemaLayout);
        panProblemaLayout.setHorizontalGroup(
            panProblemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProblemaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDescreverProblema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtDescricaoProblema, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE))
        );
        panProblemaLayout.setVerticalGroup(
            panProblemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProblemaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panProblemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edtDescricaoProblema, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(lblDescreverProblema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblSelecaoPeca.setText("Selecione 0 ou muitas peças substituídas:");

        lstPecasSubstituidas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Placa-mãe", "Processador", "Memória RAM", "HD", "SSD", "Fonte de alimentação", "Placa de vídeo", "Placas de som", "Placa de rede", "Cooler", "Ventoinhas", "Gabinete", "Placa de expansão", "Cabos", "Bateria(notebook)", "Monitor", "Teclado", "Mouse", "Webcam", "Microfone" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstPecasSubstituidas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPecasSubstituidasValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstPecasSubstituidas);

        javax.swing.GroupLayout panPecasSubstituidasLayout = new javax.swing.GroupLayout(panPecasSubstituidas);
        panPecasSubstituidas.setLayout(panPecasSubstituidasLayout);
        panPecasSubstituidasLayout.setHorizontalGroup(
            panPecasSubstituidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPecasSubstituidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelecaoPeca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        panPecasSubstituidasLayout.setVerticalGroup(
            panPecasSubstituidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPecasSubstituidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPecasSubstituidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelecaoPeca))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        panBotoes.setLayout(new javax.swing.BoxLayout(panBotoes, javax.swing.BoxLayout.LINE_AXIS));

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        panBotoes.add(btnNovo);

        btnEditar.setText("Editar");
        panBotoes.add(btnEditar);

        btnExcluir.setText("Excluir");
        panBotoes.add(btnExcluir);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panBotoes.add(btnCancelar);

        btnConfirmar.setText("Confirmar");
        panBotoes.add(btnConfirmar);

        grdTecnicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        grdTecnicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdTecnicosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(grdTecnicos);

        lblComputadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComputadores.setText("Computadores");

        lblValor.setText("Preço:");

        javax.swing.GroupLayout panValorLayout = new javax.swing.GroupLayout(panValor);
        panValor.setLayout(panValorLayout);
        panValorLayout.setHorizontalGroup(
            panValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panValorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtValor))
        );
        panValorLayout.setVerticalGroup(
            panValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panValorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComputadores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSelecaoTecnico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(panProblema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panPecasSubstituidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(lblSelecaoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSelecaoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSelecaoTecnico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panProblema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panPecasSubstituidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComputadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void grdClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdClientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_grdClientesMouseClicked

    private void grdComputadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdComputadoresMouseClicked

    }//GEN-LAST:event_grdComputadoresMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.limparCampos();
        this.habilitarCampos(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        this.habilitarCampos(true );
    }//GEN-LAST:event_btnNovoActionPerformed

    private void grdTecnicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdTecnicosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_grdTecnicosMouseClicked

    private void lstPecasSubstituidasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPecasSubstituidasValueChanged
        if (!evt.getValueIsAdjusting()) {
        // Obtém os itens selecionados na lista
        Object[] selectedItems = lstPecasSubstituidas.getSelectedValues();

            // Verifica se há itens selecionados
            if (selectedItems.length > 0) {
                // Crie uma mensagem com os itens selecionados
                StringBuilder message = new StringBuilder("Itens selecionados:\n");
                for (Object item : selectedItems) {
                    message.append(item.toString()).append("\n");
                }

                // Exibe a mensagem em um diálogo de informação
                JOptionPane.showMessageDialog(this, message.toString(), "Itens Selecionados", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_lstPecasSubstituidasValueChanged

    public void habilitarCampos(boolean flag) {
        // Labels
        lblDescreverProblema.setEnabled(flag);
        lblSelecaoCliente.setEnabled(flag);
        lblSelecaoTecnico.setEnabled(flag);
        lblSelecaoPeca.setEnabled(flag);
        lblComputadores.setEnabled(flag);
        lblValor.setEnabled(flag);
        
        // Grids
        grdClientes.setEnabled(flag);
        grdClientes.setVisible(flag);
        grdTecnicos.setEnabled(flag);
        grdTecnicos.setVisible(flag);
        grdComputadores.setEnabled(flag);
        grdComputadores.setVisible(flag);
        
        // Text Fields
        edtDescricaoProblema.setEnabled(flag);
        edtValor.setEnabled(flag);
        
        // List
        lstPecasSubstituidas.setEnabled(flag);        
    }
    
    private void limparCampos() {
        // Limpa os Edts
        edtDescricaoProblema.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgCadastrarConcertoComputador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgCadastrarConcertoComputador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgCadastrarConcertoComputador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgCadastrarConcertoComputador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                dlgCadastrarConcertoComputador dialog = new dlgCadastrarConcertoComputador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JTextField edtDescricaoProblema;
    private javax.swing.JTextField edtValor;
    private javax.swing.JTable grdClientes;
    private javax.swing.JTable grdComputadores;
    private javax.swing.JTable grdTecnicos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblComputadores;
    private javax.swing.JLabel lblDescreverProblema;
    private javax.swing.JLabel lblSelecaoCliente;
    private javax.swing.JLabel lblSelecaoPeca;
    private javax.swing.JLabel lblSelecaoTecnico;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JList<String> lstPecasSubstituidas;
    private javax.swing.JPanel panBotoes;
    private javax.swing.JPanel panPecasSubstituidas;
    private javax.swing.JPanel panProblema;
    private javax.swing.JPanel panTitulo;
    private javax.swing.JPanel panValor;
    // End of variables declaration//GEN-END:variables
}
