/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JDialog;


/**
 *
 * @author ruiz
 */
public class dlgUsuario extends javax.swing.JDialog {

    /**
     * Creates new form FrMain
     */
 
    public dlgUsuario(boolean modal){
        initComponents();
    
    }
    
    public dlgUsuario(int code) {
        initComponents();
        setModal(true);
        habilitarCamposDeAcordoComPrevilegio(code);
    }
    
    

    javax.swing.JLabel getLblUserName(){
        return this.lblUserName;
    }
    
    public void habilitarCamposDeAcordoComPrevilegio(int code){
        switch (code){
            case 1:
                   btnCadastrarTecnico.setVisible(false);
                   btnCadastrarCliente.setVisible(false);
                   btnCadastrarPeça.setVisible(false);
                   btnGerarRelatorioManutencao.setVisible(false);
                   btnCadastrarServico.setVisible(false);
                   btnRegistrarPagamento.setVisible(false);
            break;
                
            case 2: 
                btnGerarRelatorioRede.setVisible(false);
                btnSocilitarSuporte.setVisible(false);
                btnCadastrarTecnico.setVisible(false);
                btnSocilitarServico.setVisible(false);
                btnCadastrarCliente.setVisible(false);
            break;
            case 3:
                btnGerarRelatorioRede.setVisible(false);
                btnSocilitarSuporte.setVisible(false);
                btnSocilitarServico.setVisible(false);
            break;
            default: break;
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoginIcone = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        panOpcoes = new javax.swing.JPanel();
        btnGerarRelatorioManutencao = new javax.swing.JButton();
        btnCadastrarServico = new javax.swing.JButton();
        btnSocilitarSuporte = new javax.swing.JButton();
        btnGerarRelatorioRede = new javax.swing.JButton();
        btnRegistrarPagamento = new javax.swing.JButton();
        btnCadastrarPeça = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnSocilitarServico = new javax.swing.JButton();
        btnCadastrarTecnico = new javax.swing.JButton();
        btnCadastrarCliente = new javax.swing.JButton();

        lblLoginIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_85923.png"))); // NOI18N

        lblUserName.setText("nome_do_usuario");

        panOpcoes.setBackground(new java.awt.Color(102, 102, 102));
        panOpcoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panOpcoes.setLayout(new javax.swing.BoxLayout(panOpcoes, javax.swing.BoxLayout.PAGE_AXIS));

        btnGerarRelatorioManutencao.setText("Gerar Relatório de Manutenção");
        btnGerarRelatorioManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioManutencaoActionPerformed(evt);
            }
        });
        panOpcoes.add(btnGerarRelatorioManutencao);

        btnCadastrarServico.setText("Cadastrar serviço");
        btnCadastrarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarServicoActionPerformed(evt);
            }
        });
        panOpcoes.add(btnCadastrarServico);

        btnSocilitarSuporte.setText("Socilitar Suporte");
        panOpcoes.add(btnSocilitarSuporte);

        btnGerarRelatorioRede.setText("Gerar Relatório de Rede");
        panOpcoes.add(btnGerarRelatorioRede);

        btnRegistrarPagamento.setText("Registrar pagamento");
        panOpcoes.add(btnRegistrarPagamento);

        btnCadastrarPeça.setText("Cadastrar peça");
        panOpcoes.add(btnCadastrarPeça);

        jButton1.setText("Cadastrar dispositivo de rede");
        panOpcoes.add(jButton1);

        btnSocilitarServico.setText("Socilitar serviço");
        panOpcoes.add(btnSocilitarServico);

        btnCadastrarTecnico.setText("Cadastrar Tecnico");
        btnCadastrarTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarTecnicoActionPerformed(evt);
            }
        });
        panOpcoes.add(btnCadastrarTecnico);

        btnCadastrarCliente.setText("Cadastrar cliente");
        panOpcoes.add(btnCadastrarCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginIcone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panOpcoes, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLoginIcone)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panOpcoes, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarRelatorioManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioManutencaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGerarRelatorioManutencaoActionPerformed

    private void btnCadastrarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarServicoActionPerformed

    private void btnCadastrarTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarTecnicoActionPerformed
        dlgCadastrarTecnico telaTecnico = new dlgCadastrarTecnico();
        telaTecnico.setVisible(true);
    }//GEN-LAST:event_btnCadastrarTecnicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dlgUsuario(0).setVisible(true);
            }
        });
    }
    
        private void openDialog() {;
            JDialog dialog = new JDialog(this, "Dialog Example", true);
            dialog.setSize(300, 200);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCadastrarPeça;
    private javax.swing.JButton btnCadastrarServico;
    private javax.swing.JButton btnCadastrarTecnico;
    private javax.swing.JButton btnGerarRelatorioManutencao;
    private javax.swing.JButton btnGerarRelatorioRede;
    private javax.swing.JButton btnRegistrarPagamento;
    private javax.swing.JButton btnSocilitarServico;
    private javax.swing.JButton btnSocilitarSuporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblLoginIcone;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel panOpcoes;
    // End of variables declaration//GEN-END:variables
}
