/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LoginController;
import controller.UsuarioController;
import java.security.NoSuchAlgorithmException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import model.Usuario;
import utils.Criptografia;

/**
 *
 * @author ruiz
 */
public class FrLogin extends javax.swing.JFrame {
    dlgUsuario telaUsuario;
    dlgSenhaUpdate senhaupdate;
    dlgAutoCadastroCliente telaCadastroCliente;
    /**
     * Creates new form FrLogin
     */
    public FrLogin() throws ParseException {
        initComponents();
        telaCadastroCliente = new dlgAutoCadastroCliente(this, true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientPanel1 = new view.graphicElements.GradientPanel();
        jPanel1 = new javax.swing.JPanel();
        btnLogar = new view.graphicElements.BotaoVermelho();
        btnResetPassword = new view.graphicElements.BotaoVermelho();
        edtSenha = new view.graphicElements.PasswordField2();
        fEdtEmail = new view.graphicElements.FormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        lblCriarConta = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();

        setResizable(false);

        gradientPanel1.setColor1(new java.awt.Color(63, 61, 61));
        gradientPanel1.setColor2(new java.awt.Color(0, 0, 0));

        jPanel1.setOpaque(false);

        btnLogar.setBackground(new java.awt.Color(51, 51, 51));
        btnLogar.setForeground(new java.awt.Color(251, 251, 251));
        btnLogar.setText("Entrar");
        btnLogar.setBorderPainted(false);
        btnLogar.setFocusPainted(false);
        btnLogar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogar.setRadius(40);
        btnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarActionPerformed(evt);
            }
        });

        btnResetPassword.setBackground(new java.awt.Color(51, 51, 51));
        btnResetPassword.setForeground(new java.awt.Color(251, 251, 251));
        btnResetPassword.setText("Esqueci minha senha");
        btnResetPassword.setBorderPainted(false);
        btnResetPassword.setFocusPainted(false);
        btnResetPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnResetPassword.setRadius(40);
        btnResetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPasswordActionPerformed(evt);
            }
        });

        edtSenha.setBackground(new java.awt.Color(20, 20, 20));
        edtSenha.setForeground(new java.awt.Color(251, 251, 251));
        edtSenha.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        edtSenha.setLabelText("Senha");
        edtSenha.setLabelTextColor(new java.awt.Color(251, 251, 251));
        edtSenha.setLineColor(new java.awt.Color(229, 9, 20));
        edtSenha.setOpaque(false);
        edtSenha.setSelectionColor(new java.awt.Color(0, 0, 0));
        edtSenha.setShowAndHide(true);

        fEdtEmail.setBackground(new java.awt.Color(20, 20, 20));
        fEdtEmail.setForeground(new java.awt.Color(251, 251, 251));
        fEdtEmail.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        fEdtEmail.setLabelText("Email");
        fEdtEmail.setLabelTextColor(new java.awt.Color(251, 251, 251));
        fEdtEmail.setLineColor(new java.awt.Color(229, 9, 20));
        fEdtEmail.setOpaque(false);

        jLabel1.setText("Ainda não tem conta?");

        lblCriarConta.setForeground(new java.awt.Color(102, 102, 255));
        lblCriarConta.setText("Clique AQUI");
        lblCriarConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCriarContaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(btnResetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCriarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(edtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                        .addComponent(fEdtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(fEdtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCriarConta))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/8324223_ui_essential_app_avatar_profile_icon.png"))); // NOI18N

        javax.swing.GroupLayout gradientPanel1Layout = new javax.swing.GroupLayout(gradientPanel1);
        gradientPanel1.setLayout(gradientPanel1Layout);
        gradientPanel1Layout.setHorizontalGroup(
            gradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientPanel1Layout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        gradientPanel1Layout.setVerticalGroup(
            gradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fEdtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fEdtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fEdtEmailActionPerformed

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed
       try {                                         
           LoginController loginController = new LoginController();
           UsuarioController usuarioController = new UsuarioController();
           Criptografia crip = new Criptografia();
           
           try {
               loginController.validarLogin(fEdtEmail.getText(), edtSenha.getText());
               Usuario usuario = (Usuario) usuarioController.buscarUsuario(fEdtEmail.getText());
               Object obj = usuarioController.buscarUsuario(fEdtEmail.getText());
               if(crip.decrypt(usuario.getSenha()).equals(edtSenha.getText())){
                   this.setVisible(false);
                   telaUsuario = new dlgUsuario(loginController.accessManager(obj));
                   telaUsuario.getLblUserName().setText(usuario.getNome());
                   telaUsuario.setVisible(true);
                   this.setVisible(true);
                   
               }
               
               
           } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, "Email ou Senha invalidos");
               Logger.getLogger(FrLogin.class.getName()).log(Level.SEVERE, null, ex);
           }
           
           
       } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(FrLogin.class.getName()).log(Level.SEVERE,null, ex);
        }
       

    }//GEN-LAST:event_btnLogarActionPerformed

    private void btnResetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPasswordActionPerformed
       senhaupdate = new dlgSenhaUpdate( );
       senhaupdate.setVisible(true);
    }//GEN-LAST:event_btnResetPasswordActionPerformed

    private void edtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtSenhaActionPerformed

    private void lblCriarContaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCriarContaMousePressed
        // TODO add your handling code here:

        telaCadastroCliente.setVisible(true);
        
    }//GEN-LAST:event_lblCriarContaMousePressed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.graphicElements.BotaoVermelho btnLogar;
    private view.graphicElements.BotaoVermelho btnResetPassword;
    private view.graphicElements.PasswordField2 edtSenha;
    private view.graphicElements.FormattedTextField fEdtEmail;
    private view.graphicElements.GradientPanel gradientPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCriarConta;
    private javax.swing.JLabel lblIcon;
    // End of variables declaration//GEN-END:variables

    private void adicionarMascaranosCampos() throws ParseException {
        MaskFormatter emailMask = new MaskFormatter();
        //emailMask.install(fEdtEmail);

    }
}